[workspace]
members = [
    "threadpool",
    "modules",
    "channels",
    "lifetime",
    "scratch",
    "log",
    "smart-pointers",
    "error-handling",
    "flatten",
    "closure",
#    "sdl-test",
    "gat",
    "object_pool"
    "sdl-test",
    "gat",
    "anymap",
]