[package]
name = "error-handling"
version = "0.1.0"
authors = ["josueeduardo <josue.eduardo206@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.2"
serde = "1.0.124"