[package]
name = "scratch"
version = "0.1.0"
authors = ["Josh <josue.eduardo206@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4.0.1"